-- =====================================================
-- Trust Fintech Ltd - Transaction Processing Schema
-- =====================================================

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    trx_id VARCHAR(255) NOT NULL UNIQUE,

    bank_id VARCHAR(255) NOT NULL,

    customer_id BIGINT NOT NULL,

    from_account VARCHAR(255) NOT NULL,

    to_account VARCHAR(255) NOT NULL,

    amount DOUBLE PRECISION NOT NULL,

    currency VARCHAR(50) NOT NULL,

    status VARCHAR(50) NOT NULL,

    reason VARCHAR(255),

    processing_time_ms BIGINT,

    timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);

-- =====================================================
-- Indexes for performance under high concurrency
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_trx_id ON transactions(trx_id);
CREATE INDEX IF NOT EXISTS idx_bank_id ON transactions(bank_id);
CREATE INDEX IF NOT EXISTS idx_customer_id ON transactions(customer_id);